@echo off
REM Deploys the public homepage (index.html + styles.css + loyalty-view.js)
REM and the optimized reward+stamp icons to https://3ks.afkcube.com/.
REM Reads icons from packages/desktop/src/renderer/assets/loyalty/, which is
REM generated by scripts/optimize-loyalty-assets.ps1 from User-made Resources/.
setlocal
set "SSH_KEY=%USERPROFILE%\kali_openclaw"
set "REMOTE=root@76.13.215.54"
set "HERE=%~dp0"
set "ICONS=%HERE%..\desktop\src\renderer\assets\loyalty"

echo [homepage] Uploading index.html, styles.css, loyalty-view.js...
scp -i "%SSH_KEY%" "%HERE%index.html" "%HERE%styles.css" "%HERE%loyalty-view.js" %REMOTE%:/var/www/3ks.afkcube.com/ || goto :fail

echo [homepage] Ensuring /loyalty/ dir on server...
ssh -i "%SSH_KEY%" %REMOTE% "mkdir -p /var/www/3ks.afkcube.com/loyalty" || goto :fail

echo [homepage] Uploading optimized reward + stamp PNGs...
scp -i "%SSH_KEY%" "%ICONS%\medium-fries.png"     %REMOTE%:/var/www/3ks.afkcube.com/loyalty/medium-fries.png    || goto :fail
scp -i "%SSH_KEY%" "%ICONS%\large-shake.png"      %REMOTE%:/var/www/3ks.afkcube.com/loyalty/large-shake.png     || goto :fail
scp -i "%SSH_KEY%" "%ICONS%\empanada-special.png" %REMOTE%:/var/www/3ks.afkcube.com/loyalty/empanada-special.png || goto :fail
scp -i "%SSH_KEY%" "%ICONS%\stamp.png"            %REMOTE%:/var/www/3ks.afkcube.com/loyalty/stamp.png            || goto :fail

echo [homepage] Done.
exit /b 0
:fail
echo [homepage] DEPLOY FAILED
exit /b 1
